apiVersion: v1
kind: Service
metadata:
  name: {{ include "gogsapp.fullname" . }}
  labels:
    {{- include "gogsapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gogsapp.selectorLabels" . | nindent 4 }}
